repo: dongitran/elio
environment: null
type: secret

secrets:
  # MY_SECRET_KEY — describe what this secret is used for
  # Bitwarden: Folder Name/
  # - name: MY_SECRET_KEY
  #   bitwarden: MY_SECRET_KEY_BITWARDEN_NAME
