/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as AuthIndexRouteImport } from "./routes/_auth/index";
import { Route as AuthCConversationIdRouteImport } from "./routes/_auth/c.$conversationId";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRoute,
} as any);
const AuthCConversationIdRoute = AuthCConversationIdRouteImport.update({
  id: "/c/$conversationId",
  path: "/c/$conversationId",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthIndexRoute;
  "/login": typeof LoginRoute;
  "/c/$conversationId": typeof AuthCConversationIdRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/": typeof AuthIndexRoute;
  "/c/$conversationId": typeof AuthCConversationIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_auth": typeof AuthRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_auth/": typeof AuthIndexRoute;
  "/_auth/c/$conversationId": typeof AuthCConversationIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/c/$conversationId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/login" | "/" | "/c/$conversationId";
  id: "__root__" | "/_auth" | "/login" | "/_auth/" | "/_auth/c/$conversationId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/": {
      id: "/_auth/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRoute;
    };
    "/_auth/c/$conversationId": {
      id: "/_auth/c/$conversationId";
      path: "/c/$conversationId";
      fullPath: "/c/$conversationId";
      preLoaderRoute: typeof AuthCConversationIdRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute;
  AuthCConversationIdRoute: typeof AuthCConversationIdRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthCConversationIdRoute: AuthCConversationIdRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
